version: '3.8'

services:
  calculator:
    build:
      context: ../..
      dockerfile: deployment/app/App_Dockerfile
    ports:
      - "8501:8501"
    volumes:
      - ../..:/app
    restart: unless-stopped